// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZWO4jc3EbiMToUwlys3o3TAoz5_k4GTc',
    appId: '1:913925482531:web:debb17c5e57a9650e66996',
    messagingSenderId: '913925482531',
    projectId: 'jardin-de-bach',
    authDomain: 'jardin-de-bach.firebaseapp.com',
    storageBucket: 'jardin-de-bach.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA2v97QCbUaAAcQ3vFmMSewURs8b34xEo',
    appId: '1:913925482531:android:f85fe8e11473c995e66996',
    messagingSenderId: '913925482531',
    projectId: 'jardin-de-bach',
    storageBucket: 'jardin-de-bach.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoy5cs0MIWlVk7yOs7wRS5KXLmB06jwiU',
    appId: '1:913925482531:ios:c020c313ed8e039ee66996',
    messagingSenderId: '913925482531',
    projectId: 'jardin-de-bach',
    storageBucket: 'jardin-de-bach.appspot.com',
    iosClientId: '913925482531-mhmiu0hq7gfs0jb45svcoqodsa167b7t.apps.googleusercontent.com',
    iosBundleId: 'com.uaslp.jardindebach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoy5cs0MIWlVk7yOs7wRS5KXLmB06jwiU',
    appId: '1:913925482531:ios:c020c313ed8e039ee66996',
    messagingSenderId: '913925482531',
    projectId: 'jardin-de-bach',
    storageBucket: 'jardin-de-bach.appspot.com',
    iosClientId: '913925482531-mhmiu0hq7gfs0jb45svcoqodsa167b7t.apps.googleusercontent.com',
    iosBundleId: 'com.uaslp.jardindebach',
  );
}
